<?php

use Illuminate\Database\Seeder;

class CategoryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('categories')->insert(['id' => 1, 'parent_id' => 0, 'name' => 'Недвижимость']);
		DB::table('categories')->insert(['id' => 5, 'parent_id' => 0, 'name' => 'Услуги']);
		DB::table('categories')->insert(['id' => 867, 'parent_id' => 1, 'name' => 'Продаю']);
		DB::table('categories')->insert(['id' => 868, 'parent_id' => 867, 'name' => 'квартиры']);
		DB::table('categories')->insert(['id' => 883, 'parent_id' => 867, 'name' => 'комнаты']);
		DB::table('categories')->insert(['id' => 871, 'parent_id' => 867, 'name' => 'дом']);
		DB::table('categories')->insert(['id' => 872, 'parent_id' => 867, 'name' => 'гаражи']);
		DB::table('categories')->insert(['id' => 118, 'parent_id' => 1, 'name' => 'Сдаю']);
		DB::table('categories')->insert(['id' => 119, 'parent_id' => 1, 'name' => 'Меняю']);
		DB::table('categories')->insert(['id' => 125, 'parent_id' => 118, 'name' => 'квартиры']);
		DB::table('categories')->insert(['id' => 126, 'parent_id' => 118, 'name' => 'комнаты']);
		DB::table('categories')->insert(['id' => 129, 'parent_id' => 119, 'name' => 'жилье']);
		DB::table('categories')->insert(['id' => 130, 'parent_id' => 119, 'name' => 'гаражи']);
		DB::table('categories')->insert(['id' => 885, 'parent_id' => 538, 'name' => 'гаражи']);
		DB::table('categories')->insert(['id' => 169, 'parent_id' => 159, 'name' => 'Фотоаппараты']);
		DB::table('categories')->insert(['id' => 185, 'parent_id' => 175, 'name' => 'Строительство']);
		DB::table('categories')->insert(['id' => 189, 'parent_id' => 175, 'name' => 'Сантехника, газ, отопление']);
		DB::table('categories')->insert(['id' => 190, 'parent_id' => 175, 'name' => 'Электрика и антенны']);
		DB::table('categories')->insert(['id' => 191, 'parent_id' => 175, 'name' => 'Уборка, чистка']);
		DB::table('categories')->insert(['id' => 193, 'parent_id' => 176, 'name' => 'Дом и офис']);
		DB::table('categories')->insert(['id' => 194, 'parent_id' => 176, 'name' => 'Другие сотовые телефоны']);
		DB::table('categories')->insert(['id' => 198, 'parent_id' => 177, 'name' => 'Другое']);
		DB::table('categories')->insert(['id' => 202, 'parent_id' => 178, 'name' => 'Проигрыватели']);
		DB::table('categories')->insert(['id' => 932, 'parent_id' => 118, 'name' => 'гаражи']);
		DB::table('categories')->insert(['id' => 933, 'parent_id' => 539, 'name' => 'гараж']);
		DB::table('categories')->insert(['id' => 740, 'parent_id' => 739, 'name' => 'all']);
		DB::table('categories')->insert(['id' => 277, 'parent_id' => 5, 'name' => 'Юридические']);
		DB::table('categories')->insert(['id' => 774, 'parent_id' => 769, 'name' => 'Другое']);
		DB::table('categories')->insert(['id' => 1290, 'parent_id' => 1224, 'name' => 'Куплю']);
		DB::table('categories')->insert(['id' => 1291, 'parent_id' => 1224, 'name' => 'Меняю']);
		DB::table('categories')->insert(['id' => 770, 'parent_id' => 769, 'name' => 'Станки и инструменты']);
		DB::table('categories')->insert(['id' => 771, 'parent_id' => 769, 'name' => 'Для торговли и общественного питания']);
		DB::table('categories')->insert(['id' => 884, 'parent_id' => 538, 'name' => 'комнаты']);
		DB::table('categories')->insert(['id' => 462, 'parent_id' => 177, 'name' => 'Стиральные, посудомоечные машины']);
		DB::table('categories')->insert(['id' => 463, 'parent_id' => 177, 'name' => 'Пылесосы, чистящая техника']);
		DB::table('categories')->insert(['id' => 464, 'parent_id' => 177, 'name' => 'Швейные и вязальные машинки']);
		DB::table('categories')->insert(['id' => 465, 'parent_id' => 177, 'name' => 'Холодильники']);
		DB::table('categories')->insert(['id' => 466, 'parent_id' => 177, 'name' => 'Климатическая техника']);
		DB::table('categories')->insert(['id' => 467, 'parent_id' => 177, 'name' => 'Мелкая бытовая техника']);
		DB::table('categories')->insert(['id' => 468, 'parent_id' => 177, 'name' => 'Газовые и электрические плиты']);
		DB::table('categories')->insert(['id' => 470, 'parent_id' => 469, 'name' => 'Проигрыватели, рекордеры']);
		DB::table('categories')->insert(['id' => 471, 'parent_id' => 469, 'name' => 'DVD']);
		DB::table('categories')->insert(['id' => 472, 'parent_id' => 469, 'name' => 'Камеры']);
		DB::table('categories')->insert(['id' => 481, 'parent_id' => 178, 'name' => 'Акустика, колонки, усилители']);
		DB::table('categories')->insert(['id' => 483, 'parent_id' => 178, 'name' => 'Другая аудиотехника']);
		DB::table('categories')->insert(['id' => 484, 'parent_id' => 159, 'name' => 'Объективы']);
		DB::table('categories')->insert(['id' => 485, 'parent_id' => 159, 'name' => 'Аксессуары']);
		DB::table('categories')->insert(['id' => 487, 'parent_id' => 469, 'name' => 'Телевизоры и плазма']);
		DB::table('categories')->insert(['id' => 772, 'parent_id' => 769, 'name' => 'Для парикмахерских и салонов красоты']);
		DB::table('categories')->insert(['id' => 538, 'parent_id' => 1, 'name' => 'Куплю']);
		DB::table('categories')->insert(['id' => 539, 'parent_id' => 1, 'name' => 'Сниму']);
		DB::table('categories')->insert(['id' => 875, 'parent_id' => 118, 'name' => 'дома']);
		DB::table('categories')->insert(['id' => 886, 'parent_id' => 119, 'name' => 'зем. участки']);
		DB::table('categories')->insert(['id' => 547, 'parent_id' => 538, 'name' => 'дома']);
		DB::table('categories')->insert(['id' => 548, 'parent_id' => 538, 'name' => 'доли']);
		DB::table('categories')->insert(['id' => 554, 'parent_id' => 538, 'name' => 'квартиры']);
		DB::table('categories')->insert(['id' => 558, 'parent_id' => 539, 'name' => 'квартиры']);
		DB::table('categories')->insert(['id' => 559, 'parent_id' => 539, 'name' => 'комнаты']);
		DB::table('categories')->insert(['id' => 877, 'parent_id' => 539, 'name' => 'дома']);
		DB::table('categories')->insert(['id' => 878, 'parent_id' => 867, 'name' => 'доли']);
		DB::table('categories')->insert(['id' => 791, 'parent_id' => 176, 'name' => 'Acer']);
		DB::table('categories')->insert(['id' => 792, 'parent_id' => 176, 'name' => 'Alcatel']);
		DB::table('categories')->insert(['id' => 793, 'parent_id' => 176, 'name' => 'Apple']);
		DB::table('categories')->insert(['id' => 794, 'parent_id' => 176, 'name' => 'ASUS']);
		DB::table('categories')->insert(['id' => 795, 'parent_id' => 176, 'name' => 'BlackBerry']);
		DB::table('categories')->insert(['id' => 796, 'parent_id' => 176, 'name' => 'Fly']);
		DB::table('categories')->insert(['id' => 797, 'parent_id' => 176, 'name' => 'HTC']);
		DB::table('categories')->insert(['id' => 798, 'parent_id' => 176, 'name' => 'LG']);
		DB::table('categories')->insert(['id' => 799, 'parent_id' => 176, 'name' => 'Motorola']);
		DB::table('categories')->insert(['id' => 800, 'parent_id' => 176, 'name' => 'Nokia']);
		DB::table('categories')->insert(['id' => 801, 'parent_id' => 176, 'name' => 'Palm']);
		DB::table('categories')->insert(['id' => 802, 'parent_id' => 176, 'name' => 'Pantech']);
		DB::table('categories')->insert(['id' => 803, 'parent_id' => 176, 'name' => 'Philips']);
		DB::table('categories')->insert(['id' => 804, 'parent_id' => 176, 'name' => 'Sagem']);
		DB::table('categories')->insert(['id' => 805, 'parent_id' => 176, 'name' => 'Samsung']);
		DB::table('categories')->insert(['id' => 806, 'parent_id' => 176, 'name' => 'SonyEricsson']);
		DB::table('categories')->insert(['id' => 807, 'parent_id' => 176, 'name' => 'Vertu']);
		DB::table('categories')->insert(['id' => 808, 'parent_id' => 176, 'name' => 'Билайн']);
		DB::table('categories')->insert(['id' => 809, 'parent_id' => 176, 'name' => 'МегаФон']);
		DB::table('categories')->insert(['id' => 810, 'parent_id' => 176, 'name' => 'МТС']);
		DB::table('categories')->insert(['id' => 811, 'parent_id' => 176, 'name' => 'Контракты операторов']);
		DB::table('categories')->insert(['id' => 812, 'parent_id' => 176, 'name' => 'Разное']);
		DB::table('categories')->insert(['id' => 816, 'parent_id' => 176, 'name' => 'Радиостанции и рации']);
		DB::table('categories')->insert(['id' => 817, 'parent_id' => 176, 'name' => 'Аксессуары для телефонов']);
		DB::table('categories')->insert(['id' => 1036, 'parent_id' => 867, 'name' => 'зем. участки']);
		DB::table('categories')->insert(['id' => 1038, 'parent_id' => 538, 'name' => 'зем. участки']);
		DB::table('categories')->insert(['id' => 1040, 'parent_id' => 118, 'name' => 'зем. участки']);
		DB::table('categories')->insert(['id' => 1041, 'parent_id' => 539, 'name' => 'зем. участки']);
		DB::table('categories')->insert(['id' => 1042, 'parent_id' => 0, 'name' => 'Дом']);
		DB::table('categories')->insert(['id' => 1043, 'parent_id' => 0, 'name' => 'Электроника']);
		DB::table('categories')->insert(['id' => 1045, 'parent_id' => 1043, 'name' => 'Продаю']);
		DB::table('categories')->insert(['id' => 1046, 'parent_id' => 1043, 'name' => 'Куплю']);
		DB::table('categories')->insert(['id' => 1047, 'parent_id' => 0, 'name' => 'Коммерческая недвижимость. Бизнес']);
		DB::table('categories')->insert(['id' => 1048, 'parent_id' => 1045, 'name' => 'бытовая техника']);
		DB::table('categories')->insert(['id' => 1049, 'parent_id' => 1047, 'name' => 'Продаю']);
		DB::table('categories')->insert(['id' => 1050, 'parent_id' => 1047, 'name' => 'Куплю']);
		DB::table('categories')->insert(['id' => 1051, 'parent_id' => 1045, 'name' => 'компьютеры и оргтехника']);
		DB::table('categories')->insert(['id' => 1052, 'parent_id' => 1047, 'name' => 'Аренда']);
		DB::table('categories')->insert(['id' => 1053, 'parent_id' => 1045, 'name' => 'связь']);
		DB::table('categories')->insert(['id' => 1054, 'parent_id' => 1049, 'name' => 'здание']);
		DB::table('categories')->insert(['id' => 1055, 'parent_id' => 1049, 'name' => 'бокс']);
		DB::table('categories')->insert(['id' => 1056, 'parent_id' => 1049, 'name' => 'склад']);
		DB::table('categories')->insert(['id' => 1057, 'parent_id' => 1045, 'name' => 'аудио, фото, видео']);
		DB::table('categories')->insert(['id' => 1058, 'parent_id' => 1049, 'name' => 'производственная база']);
		DB::table('categories')->insert(['id' => 1059, 'parent_id' => 1049, 'name' => 'помещение']);
		DB::table('categories')->insert(['id' => 1060, 'parent_id' => 1046, 'name' => 'бытовая техника']);
		DB::table('categories')->insert(['id' => 1061, 'parent_id' => 1049, 'name' => 'зем. участок']);
		DB::table('categories')->insert(['id' => 1062, 'parent_id' => 1049, 'name' => 'бизнес, оборудование для бизнеса']);
		DB::table('categories')->insert(['id' => 1063, 'parent_id' => 1046, 'name' => 'компьютеры и оргтехника']);
		DB::table('categories')->insert(['id' => 1064, 'parent_id' => 1049, 'name' => 'другое']);
		DB::table('categories')->insert(['id' => 1065, 'parent_id' => 1050, 'name' => 'здание']);
		DB::table('categories')->insert(['id' => 1066, 'parent_id' => 1046, 'name' => 'связь']);
		DB::table('categories')->insert(['id' => 1067, 'parent_id' => 1050, 'name' => 'бокс']);
		DB::table('categories')->insert(['id' => 1068, 'parent_id' => 1050, 'name' => 'склад']);
		DB::table('categories')->insert(['id' => 1069, 'parent_id' => 1046, 'name' => 'аудио, фото, видео']);
		DB::table('categories')->insert(['id' => 1070, 'parent_id' => 1050, 'name' => 'производственная база']);
		DB::table('categories')->insert(['id' => 1071, 'parent_id' => 1042, 'name' => 'Продаю']);
		DB::table('categories')->insert(['id' => 1072, 'parent_id' => 1050, 'name' => 'помещение']);
		DB::table('categories')->insert(['id' => 1073, 'parent_id' => 1042, 'name' => 'Куплю']);
		DB::table('categories')->insert(['id' => 1074, 'parent_id' => 1050, 'name' => 'зем. участок']);
		DB::table('categories')->insert(['id' => 1075, 'parent_id' => 1050, 'name' => 'бизнес, оборудование для бизнеса']);
		DB::table('categories')->insert(['id' => 1076, 'parent_id' => 5, 'name' => 'Изготовление и ремонт мебели']);
		DB::table('categories')->insert(['id' => 1077, 'parent_id' => 1050, 'name' => 'другое']);
		DB::table('categories')->insert(['id' => 1078, 'parent_id' => 1052, 'name' => 'здание']);
		DB::table('categories')->insert(['id' => 1079, 'parent_id' => 1052, 'name' => 'бокс']);
		DB::table('categories')->insert(['id' => 1080, 'parent_id' => 1052, 'name' => 'склад']);
		DB::table('categories')->insert(['id' => 1081, 'parent_id' => 1071, 'name' => 'мебель']);
		DB::table('categories')->insert(['id' => 1082, 'parent_id' => 1052, 'name' => 'производственная база']);
		DB::table('categories')->insert(['id' => 1083, 'parent_id' => 1071, 'name' => 'растения']);
		DB::table('categories')->insert(['id' => 1084, 'parent_id' => 1052, 'name' => 'помещение']);
		DB::table('categories')->insert(['id' => 1085, 'parent_id' => 1052, 'name' => 'зем. участок']);
		DB::table('categories')->insert(['id' => 1086, 'parent_id' => 1052, 'name' => 'бизнес, оборудование для бизнеса']);
		DB::table('categories')->insert(['id' => 1087, 'parent_id' => 1052, 'name' => 'другое']);
		DB::table('categories')->insert(['id' => 1088, 'parent_id' => 0, 'name' => 'Авто']);
		DB::table('categories')->insert(['id' => 1089, 'parent_id' => 1088, 'name' => 'Продаю']);
		DB::table('categories')->insert(['id' => 1090, 'parent_id' => 1071, 'name' => 'предметы быта, интерьера']);
		DB::table('categories')->insert(['id' => 1091, 'parent_id' => 1088, 'name' => 'Куплю']);
		DB::table('categories')->insert(['id' => 1092, 'parent_id' => 1088, 'name' => 'Аренда']);
		DB::table('categories')->insert(['id' => 1093, 'parent_id' => 1071, 'name' => 'посуда']);
		DB::table('categories')->insert(['id' => 1094, 'parent_id' => 5, 'name' => 'Грузоперевозки']);
		DB::table('categories')->insert(['id' => 1095, 'parent_id' => 1071, 'name' => 'другое']);
		DB::table('categories')->insert(['id' => 1096, 'parent_id' => 1089, 'name' => 'легковые автомобили']);
		DB::table('categories')->insert(['id' => 1097, 'parent_id' => 1073, 'name' => 'мебель']);
		DB::table('categories')->insert(['id' => 1098, 'parent_id' => 1089, 'name' => 'спецтехника']);
		DB::table('categories')->insert(['id' => 1099, 'parent_id' => 1073, 'name' => 'растения']);
		DB::table('categories')->insert(['id' => 1100, 'parent_id' => 1089, 'name' => 'водный транспорт']);
		DB::table('categories')->insert(['id' => 1101, 'parent_id' => 1089, 'name' => 'мототехника']);
		DB::table('categories')->insert(['id' => 1102, 'parent_id' => 1073, 'name' => 'предметы быта, интерьера']);
		DB::table('categories')->insert(['id' => 1103, 'parent_id' => 1089, 'name' => 'запчасти и аксессуары']);
		DB::table('categories')->insert(['id' => 1104, 'parent_id' => 1073, 'name' => 'посуда']);
		DB::table('categories')->insert(['id' => 1105, 'parent_id' => 1091, 'name' => 'легковые автомобили']);
		DB::table('categories')->insert(['id' => 1106, 'parent_id' => 1073, 'name' => 'другое']);
		DB::table('categories')->insert(['id' => 1107, 'parent_id' => 0, 'name' => 'Дача. Урожай']);
		DB::table('categories')->insert(['id' => 1108, 'parent_id' => 1091, 'name' => 'водный транспорт']);
		DB::table('categories')->insert(['id' => 1109, 'parent_id' => 1107, 'name' => 'Продаю']);
		DB::table('categories')->insert(['id' => 1110, 'parent_id' => 1091, 'name' => 'мототехника']);
		DB::table('categories')->insert(['id' => 1111, 'parent_id' => 1107, 'name' => 'Куплю']);
		DB::table('categories')->insert(['id' => 1112, 'parent_id' => 1091, 'name' => 'спецтехника']);
		DB::table('categories')->insert(['id' => 1113, 'parent_id' => 1091, 'name' => 'запчасти и аксессуары']);
		DB::table('categories')->insert(['id' => 1114, 'parent_id' => 1092, 'name' => 'сдаю']);
		DB::table('categories')->insert(['id' => 1115, 'parent_id' => 1109, 'name' => 'продукты питания']);
		DB::table('categories')->insert(['id' => 1116, 'parent_id' => 1092, 'name' => 'сниму']);
		DB::table('categories')->insert(['id' => 1118, 'parent_id' => 1109, 'name' => 'садовый инвентарь']);
		DB::table('categories')->insert(['id' => 1120, 'parent_id' => 1109, 'name' => 'техника']);
		DB::table('categories')->insert(['id' => 1122, 'parent_id' => 1109, 'name' => 'дачный интерьер']);
		DB::table('categories')->insert(['id' => 1123, 'parent_id' => 1109, 'name' => 'растения']);
		DB::table('categories')->insert(['id' => 1124, 'parent_id' => 1109, 'name' => 'другое']);
		DB::table('categories')->insert(['id' => 1125, 'parent_id' => 0, 'name' => 'Детское']);
		DB::table('categories')->insert(['id' => 1126, 'parent_id' => 1125, 'name' => 'Продаю']);
		DB::table('categories')->insert(['id' => 1127, 'parent_id' => 5, 'name' => 'Установка, ремонт бытовой техники']);
		DB::table('categories')->insert(['id' => 1128, 'parent_id' => 1125, 'name' => 'Куплю']);
		DB::table('categories')->insert(['id' => 1129, 'parent_id' => 5, 'name' => 'Услуги по уходу']);
		DB::table('categories')->insert(['id' => 1130, 'parent_id' => 5, 'name' => 'Образовательные']);
		DB::table('categories')->insert(['id' => 1131, 'parent_id' => 1126, 'name' => 'одежда, обувь']);
		DB::table('categories')->insert(['id' => 1132, 'parent_id' => 5, 'name' => 'Компьютерные']);
		DB::table('categories')->insert(['id' => 1133, 'parent_id' => 1126, 'name' => 'коляски']);
		DB::table('categories')->insert(['id' => 1134, 'parent_id' => 1126, 'name' => 'кроватки']);
		DB::table('categories')->insert(['id' => 1135, 'parent_id' => 5, 'name' => 'Праздничные']);
		DB::table('categories')->insert(['id' => 1136, 'parent_id' => 5, 'name' => 'Услуги по красоте']);
		DB::table('categories')->insert(['id' => 1138, 'parent_id' => 5, 'name' => 'Бухгалтерские']);
		DB::table('categories')->insert(['id' => 1139, 'parent_id' => 1126, 'name' => 'игрушки']);
		DB::table('categories')->insert(['id' => 1140, 'parent_id' => 5, 'name' => 'Услуги по прописке']);
		DB::table('categories')->insert(['id' => 1141, 'parent_id' => 5, 'name' => 'Прочие']);
		DB::table('categories')->insert(['id' => 1142, 'parent_id' => 1126, 'name' => 'другое']);
		DB::table('categories')->insert(['id' => 1143, 'parent_id' => 1128, 'name' => 'одежда, обувь']);
		DB::table('categories')->insert(['id' => 1144, 'parent_id' => 1128, 'name' => 'коляски']);
		DB::table('categories')->insert(['id' => 1145, 'parent_id' => 1128, 'name' => 'кроватки']);
		DB::table('categories')->insert(['id' => 1148, 'parent_id' => 1128, 'name' => 'игрушки']);
		DB::table('categories')->insert(['id' => 1150, 'parent_id' => 1128, 'name' => 'другое']);
		DB::table('categories')->insert(['id' => 1152, 'parent_id' => 0, 'name' => 'Одежда. Аксессуары']);
		DB::table('categories')->insert(['id' => 1154, 'parent_id' => 1152, 'name' => 'Продаю']);
		DB::table('categories')->insert(['id' => 1156, 'parent_id' => 1152, 'name' => 'Куплю']);
		DB::table('categories')->insert(['id' => 1158, 'parent_id' => 5, 'name' => 'Пошив, ремонт одежды']);
		DB::table('categories')->insert(['id' => 1161, 'parent_id' => 1154, 'name' => 'одежда']);
		DB::table('categories')->insert(['id' => 1164, 'parent_id' => 1154, 'name' => 'аксессуары']);
		DB::table('categories')->insert(['id' => 1167, 'parent_id' => 1156, 'name' => 'одежда']);
		DB::table('categories')->insert(['id' => 1169, 'parent_id' => 1156, 'name' => 'головные уборы']);
		DB::table('categories')->insert(['id' => 1170, 'parent_id' => 1156, 'name' => 'обувь']);
		DB::table('categories')->insert(['id' => 1171, 'parent_id' => 1156, 'name' => 'аксессуары']);
		DB::table('categories')->insert(['id' => 1173, 'parent_id' => 0, 'name' => 'Хобби. Отдых. Спорт']);
		DB::table('categories')->insert(['id' => 1175, 'parent_id' => 1173, 'name' => 'Продаю']);
		DB::table('categories')->insert(['id' => 1176, 'parent_id' => 1173, 'name' => 'Куплю']);
		DB::table('categories')->insert(['id' => 1177, 'parent_id' => 1175, 'name' => 'литература']);
		DB::table('categories')->insert(['id' => 1178, 'parent_id' => 1175, 'name' => 'все музыкальное']);
		DB::table('categories')->insert(['id' => 1179, 'parent_id' => 1175, 'name' => 'спорт, туризм']);
		DB::table('categories')->insert(['id' => 1180, 'parent_id' => 1175, 'name' => 'охота и рыбалка']);
		DB::table('categories')->insert(['id' => 1181, 'parent_id' => 1175, 'name' => 'другое']);
		DB::table('categories')->insert(['id' => 1182, 'parent_id' => 1176, 'name' => 'литература']);
		DB::table('categories')->insert(['id' => 1183, 'parent_id' => 1176, 'name' => 'все музыкальное']);
		DB::table('categories')->insert(['id' => 1184, 'parent_id' => 1176, 'name' => 'спорт, туризм']);
		DB::table('categories')->insert(['id' => 1185, 'parent_id' => 1176, 'name' => 'охота и рыбалка']);
		DB::table('categories')->insert(['id' => 1186, 'parent_id' => 1176, 'name' => 'другое']);
		DB::table('categories')->insert(['id' => 1187, 'parent_id' => 0, 'name' => 'Животные']);
		DB::table('categories')->insert(['id' => 1188, 'parent_id' => 1187, 'name' => 'Продаю']);
		DB::table('categories')->insert(['id' => 1189, 'parent_id' => 1187, 'name' => 'Куплю']);
		DB::table('categories')->insert(['id' => 1190, 'parent_id' => 1187, 'name' => 'Отдам']);
		DB::table('categories')->insert(['id' => 1191, 'parent_id' => 1187, 'name' => 'Возьму в дар']);
		DB::table('categories')->insert(['id' => 1192, 'parent_id' => 1187, 'name' => 'Вязка']);
		DB::table('categories')->insert(['id' => 1193, 'parent_id' => 1187, 'name' => 'Услуги для животных']);
		DB::table('categories')->insert(['id' => 1194, 'parent_id' => 1188, 'name' => 'собаки']);
		DB::table('categories')->insert(['id' => 1195, 'parent_id' => 1188, 'name' => 'кошки']);
		DB::table('categories')->insert(['id' => 1196, 'parent_id' => 1188, 'name' => 'птицы']);
		DB::table('categories')->insert(['id' => 1197, 'parent_id' => 1188, 'name' => 'аквариумные рыбы']);
		DB::table('categories')->insert(['id' => 1198, 'parent_id' => 1188, 'name' => 'другие животные']);
		DB::table('categories')->insert(['id' => 1199, 'parent_id' => 1188, 'name' => 'товары для животных']);
		DB::table('categories')->insert(['id' => 1200, 'parent_id' => 1189, 'name' => 'собаки']);
		DB::table('categories')->insert(['id' => 1201, 'parent_id' => 1189, 'name' => 'кошки']);
		DB::table('categories')->insert(['id' => 1202, 'parent_id' => 1189, 'name' => 'птицы']);
		DB::table('categories')->insert(['id' => 1203, 'parent_id' => 1189, 'name' => 'аквариумные рыбы']);
		DB::table('categories')->insert(['id' => 1204, 'parent_id' => 1189, 'name' => 'другие животные']);
		DB::table('categories')->insert(['id' => 1205, 'parent_id' => 1189, 'name' => 'товары для животных']);
		DB::table('categories')->insert(['id' => 1206, 'parent_id' => 1192, 'name' => 'собаки']);
		DB::table('categories')->insert(['id' => 1207, 'parent_id' => 1192, 'name' => 'кошки']);
		DB::table('categories')->insert(['id' => 1208, 'parent_id' => 1192, 'name' => 'другие животные']);
		DB::table('categories')->insert(['id' => 1209, 'parent_id' => 0, 'name' => 'Ищу людей']);
		DB::table('categories')->insert(['id' => 1210, 'parent_id' => 1209, 'name' => 'На подселение']);
		DB::table('categories')->insert(['id' => 1211, 'parent_id' => 1209, 'name' => 'Попутчика']);
		DB::table('categories')->insert(['id' => 1212, 'parent_id' => 1209, 'name' => 'Партнера для бизнеса']);
		DB::table('categories')->insert(['id' => 1213, 'parent_id' => 1209, 'name' => 'Партнера по интересам']);
		DB::table('categories')->insert(['id' => 1214, 'parent_id' => 1209, 'name' => 'Свидетелей']);
		DB::table('categories')->insert(['id' => 1215, 'parent_id' => 1209, 'name' => 'Другое']);
		DB::table('categories')->insert(['id' => 1216, 'parent_id' => 0, 'name' => 'Знакомства']);
		DB::table('categories')->insert(['id' => 1217, 'parent_id' => 1216, 'name' => 'Ищу ее']);
		DB::table('categories')->insert(['id' => 1218, 'parent_id' => 1216, 'name' => 'Ищу его']);
		DB::table('categories')->insert(['id' => 1219, 'parent_id' => 0, 'name' => 'Пропажи. Находки']);
		DB::table('categories')->insert(['id' => 1220, 'parent_id' => 1219, 'name' => 'Личные вещи']);
		DB::table('categories')->insert(['id' => 1221, 'parent_id' => 1219, 'name' => 'Документы']);
		DB::table('categories')->insert(['id' => 1222, 'parent_id' => 1219, 'name' => 'Животные']);
		DB::table('categories')->insert(['id' => 1223, 'parent_id' => 1219, 'name' => 'Другое']);
		DB::table('categories')->insert(['id' => 1224, 'parent_id' => 0, 'name' => 'Разное']);
		DB::table('categories')->insert(['id' => 1225, 'parent_id' => 1224, 'name' => 'Дарю']);
		DB::table('categories')->insert(['id' => 1226, 'parent_id' => 1224, 'name' => 'Возьму в дар']);
		DB::table('categories')->insert(['id' => 1227, 'parent_id' => 1224, 'name' => 'Сообщения']);
		DB::table('categories')->insert(['id' => 1229, 'parent_id' => 0, 'name' => 'Строительство. Ремонт']);
		DB::table('categories')->insert(['id' => 1230, 'parent_id' => 5, 'name' => 'Строительные']);
		DB::table('categories')->insert(['id' => 1231, 'parent_id' => 1229, 'name' => 'Продаю']);
		DB::table('categories')->insert(['id' => 1232, 'parent_id' => 1229, 'name' => 'Куплю']);
		DB::table('categories')->insert(['id' => 1233, 'parent_id' => 1231, 'name' => 'готовые изделия']);
		DB::table('categories')->insert(['id' => 1234, 'parent_id' => 1231, 'name' => 'строительные и отделочные материалы']);
		DB::table('categories')->insert(['id' => 1235, 'parent_id' => 1231, 'name' => 'контейнеры, емкости']);
		DB::table('categories')->insert(['id' => 1236, 'parent_id' => 1231, 'name' => 'станки, инструменты']);
		DB::table('categories')->insert(['id' => 1237, 'parent_id' => 1231, 'name' => 'другое']);
		DB::table('categories')->insert(['id' => 1238, 'parent_id' => 1232, 'name' => 'готовые изделия']);
		DB::table('categories')->insert(['id' => 1239, 'parent_id' => 1232, 'name' => 'строительные и отделочные материалы']);
		DB::table('categories')->insert(['id' => 1240, 'parent_id' => 1232, 'name' => 'контейнеры, емкости']);
		DB::table('categories')->insert(['id' => 1241, 'parent_id' => 1232, 'name' => 'станки, инструменты']);
		DB::table('categories')->insert(['id' => 1242, 'parent_id' => 1232, 'name' => 'другое']);
		DB::table('categories')->insert(['id' => 1285, 'parent_id' => 1154, 'name' => 'обувь']);
		DB::table('categories')->insert(['id' => 1243, 'parent_id' => 0, 'name' => 'Работа']);
		DB::table('categories')->insert(['id' => 1244, 'parent_id' => 1243, 'name' => 'Вакансии']);
		DB::table('categories')->insert(['id' => 1245, 'parent_id' => 1243, 'name' => 'Резюме']);
		DB::table('categories')->insert(['id' => 1283, 'parent_id' => 1045, 'name' => 'другое']);
		DB::table('categories')->insert(['id' => 1284, 'parent_id' => 1109, 'name' => 'садовая мебель']);
		DB::table('categories')->insert(['id' => 1286, 'parent_id' => 1154, 'name' => 'головные уборы']);
		DB::table('categories')->insert(['id' => 1289, 'parent_id' => 1046, 'name' => 'другое']);
		DB::table('categories')->insert(['id' => 1318, 'parent_id' => 1126, 'name' => 'автокресла']);
		DB::table('categories')->insert(['id' => 1319, 'parent_id' => 1128, 'name' => 'автокресла']);
		DB::table('categories')->insert(['id' => 1320, 'parent_id' => 1089, 'name' => 'грузовые автомобили']);
		DB::table('categories')->insert(['id' => 1321, 'parent_id' => 1091, 'name' => 'грузовые автомобили']);
		DB::table('categories')->insert(['id' => 1322, 'parent_id' => 1089, 'name' => 'автобусы']);
		DB::table('categories')->insert(['id' => 1323, 'parent_id' => 1091, 'name' => 'автобусы']);
		DB::table('categories')->insert(['id' => 1324, 'parent_id' => 1188, 'name' => 'грызуны']);
		DB::table('categories')->insert(['id' => 1325, 'parent_id' => 1189, 'name' => 'грызуны']);
		DB::table('categories')->insert(['id' => 1326, 'parent_id' => 1188, 'name' => 'рептилии']);
		DB::table('categories')->insert(['id' => 1327, 'parent_id' => 1189, 'name' => 'рептилии']);
		DB::table('categories')->insert(['id' => 1328, 'parent_id' => 1175, 'name' => 'коллекционирование']);
		DB::table('categories')->insert(['id' => 1329, 'parent_id' => 1176, 'name' => 'коллекционирование']);
		DB::table('categories')->insert(['id' => 1330, 'parent_id' => 1224, 'name' => 'Продаю']);
		DB::table('categories')->insert(['id' => 1331, 'parent_id' => 1088, 'name' => 'Обмен']);
		DB::table('categories')->insert(['id' => 1332, 'parent_id' => 1089, 'name' => 'авто на запчасти']);
		DB::table('categories')->insert(['id' => 1333, 'parent_id' => 1091, 'name' => 'авто на запчасти']);
		DB::table('categories')->insert(['id' => 1338, 'parent_id' => 1224, 'name' => 'Аренда']);
    }
}